CREATE TABLE [dbo].[FormEntry]
(
	[RecordGUID] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT (newid()), 
    [Name] VARCHAR(30) NOT NULL DEFAULT '',
    [ref_Horse1] UNIQUEIDENTIFIER NOT NULL,
	[ref_Horse2] UNIQUEIDENTIFIER NOT NULL, 
    [ref_Horse3] UNIQUEIDENTIFIER NOT NULL, 
	[ref_Category] UNIQUEIDENTIFIER NOT NULL, 
    [Music] VARBINARY(MAX) NOT NULL DEFAULT 0xFFFFFFFF , 
    CONSTRAINT FK_ref_Horse1 FOREIGN KEY ([ref_Horse1]) REFERENCES Horses(RecordGUID),
	CONSTRAINT FK_ref_Horse2 FOREIGN KEY ([ref_Horse2]) REFERENCES Horses(RecordGUID),
	CONSTRAINT FK_ref_Horse3 FOREIGN KEY ([ref_Horse3]) REFERENCES Horses(RecordGUID),
	CONSTRAINT FK_ref_Category FOREIGN KEY ([ref_Category]) REFERENCES Category(RecordGUID)
)
