CREATE TABLE [dbo].[FormEntry]
(
	[RecordGUID] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT (newid()), 
    [Name] VARCHAR(30) NOT NULL, 
    [Phone] VARCHAR(12) NOT NULL, 
    [ref_Horse1] UNIQUEIDENTIFIER NOT NULL,
	[ref_Horse2] UNIQUEIDENTIFIER NOT NULL, 
    [ref_Horse3] UNIQUEIDENTIFIER NOT NULL, 
    CONSTRAINT FK_ref_Horse1 FOREIGN KEY ([ref_Horse1]) REFERENCES Horses(RecordGUID),
	CONSTRAINT FK_ref_Horse2 FOREIGN KEY ([ref_Horse2]) REFERENCES Horses(RecordGUID),
	CONSTRAINT FK_ref_Horse3 FOREIGN KEY ([ref_Horse3]) REFERENCES Horses(RecordGUID)
)
